services:
  - type: web
    name: blomoto-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn blomotobackend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: DJANGO_SETTINGS_MODULE
        value: blomotobackend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com" 