# Generated by Django 5.1.7 on 2025-03-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
