# Generated by Django 5.0.7 on 2025-03-18 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_category'),
        ('user_app', '0002_avis_rendezvous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='service_app.service'),
        ),
    ]
