# Generated by Django 5.1.7 on 2025-03-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_rendezvous_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
