# Generated by Django 5.0.7 on 2025-03-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_category_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='comment',
        ),
        migrations.AddField(
            model_name='service',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
