# Generated by Django 5.1.7 on 2025-03-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_app.service')),
            ],
            options={
                'verbose_name': 'Garage',
                'verbose_name_plural': 'Garage',
            },
        ),
    ]
