# Generated by Django 5.0.7 on 2025-03-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('garage_picture', models.ImageField(blank=True, null=True, upload_to='garages_pictures/')),
                ('service', models.ManyToManyField(blank=True, related_name='service', to='service_app.service')),
            ],
            options={
                'verbose_name': 'Garage',
                'verbose_name_plural': 'Garage',
            },
        ),
    ]
