# Generated by Django 5.1.7 on 2025-03-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0001_initial'),
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='service',
        ),
        migrations.AddField(
            model_name='garage',
            name='service',
            field=models.ManyToManyField(related_name='garage', to='service_app.service'),
        ),
    ]
