# Generated by Django 5.0.7 on 2025-03-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0002_remove_garage_service_garage_service'),
        ('service_app', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='service',
        ),
        migrations.AddField(
            model_name='garage',
            name='categorie',
            field=models.ManyToManyField(blank=True, related_name='garage', to='service_app.category'),
        ),
    ]
