# Generated by Django 5.1.7 on 2025-03-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0003_remove_garage_service_garage_categorie'),
        ('service_app', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='categorie',
        ),
        migrations.AddField(
            model_name='garage',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='service', to='service_app.service'),
        ),
    ]
